### ISSUE TITLE
Can't play some VEVO videos

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#62] opened 2015-05-16 00:25 UTC
Example:
https://www.youtube.com/watch?v=eXvBjCO19QY

I get the "E".

Firefox 38
Win 7 x64

TIA.

**Comment by Sonic0170** [comment] 2015-05-16 00:54
thats odd, im still on ff 37 cause i havent updated yet, so it must be something in firefox changed

**Comment by Sonic0170** [comment] 2015-05-16 01:06
nope i am able to play it without issue, don't know what to tell you @LL25255252

**Comment by LL25255252** [comment] 2015-05-16 01:50
@Sonic0170 thanks for your help.
It turns out that on a fresh/clean profile VLCtube does play the video. So probably I have some addon that cause it.
I just found a workaround to play these VEVO videos. After I get an "E" I change the quality (VLC's drop down menu) to any other quality and the video start to play. 
Also it doesn't matter which format priority map I set.
As soon as I have time I'll try to investigate it more.

**Comment by LL25255252** [comment] 2015-05-18 12:28
I removed youtube.com cookies and the problem is solved.

**Comment by LL25255252** [comment] 2015-05-19 14:26
As far as I'm concerned, this issue can now be closed.

**Comment by jackun** [comment] 2015-05-19 14:31
Oh right, duplicate of #34? ;P

I'd use #34 for these kinds of errors.

**Closed by jackun** 2015-05-19 14:31 UTC
